In [44]:
import pandas as pd
data = pd.read_csv("Manglish.csv")


In [52]:
import numpy as np
train_data, val_data, test_data = np.split(data.sample(frac=1, random_state=42), [int(.6*len(data)), int(.8*len(data))])

In [53]:
train_data=train_data.astype(str)
test_data=test_data.astype(str)
val_data=val_data.astype(str)

In [54]:
train_data

text    target
438      Nattellullengile pothu samuhathil parayan pattu   Neutral
9389      Villainm villainte monum orumich padkuayrikm..   Neutral
385    Kerala politicsile Shigandi ennu vazhthapedatt...  Negative
10218                          Ne troln allne enke aryam   Neutral
11091  Likes um subscribers um kuravanelum viewers ne...  Negative
...                                                  ...       ...
14872  Pwoliyeaaa ❤️❤️❤️❤️❤️.....Adithyan ivada indoo...  Positive
17128  Uppum mulakum Continue aayit kaanan pattiyirun...  Positive
3587   Vaaye thonniyathalla ayalude massilullatha vil...   Neutral
11775                                          Arun uyir  Positive
15725  Namichuuuuuu sajeesh atta👏👏👏👍👍👍👍👍👍👍👍👍👍😍😍😘😘...g...  Positive

[11473 rows x 2 columns]

In [60]:
test_data

text    target
18481                        Superb & promising  trailer  Positive
5485   Chilar evide chennalum avide kolamakkyitte adangu  Negative
6136   Shiksha kuranju poyi achanum ammakkum nashtama...  Negative
10976                                    Ivanu pranthano  Negative
5694   Avande familiyilullavar ithilum kashttamayirikkum  Negative
...                                                  ...       ...
11284                                 Endh veruppikalada  Negative
11964  Uyoo ende monee 😂😂 kuduthaal kuduthal prathesh...  Positive
5390                                       Abilash sanki   Neutral
860                        Ayala aara thurannu vitta...😠   Neutral
15795                                  Poliyeeeeeeeee❤💪💪  Positive

[3825 rows x 2 columns]

In [56]:
val_data

text    target
10962                                Shonnan nee ahda🤣🤣🤣  Negative
10185  Kuree naalinu shesham aanu like nw kkal koodut...   Neutral
324    lulu vannal mattu cheriya kachavadakkaar poott...   Neutral
7890   Chettan nice aayit amazonil kaanicha price cut...   Neutral
5171   Soudhi arabia vare maari evide sthreekal epol ...   Neutral
...                                                  ...       ...
10442  Elaavarum inghane fukruvine kuttam parayalle.....   Neutral
14631                       Enikku onnu support cheyyamo   Neutral
4897                                     Muslim myranmar  Negative
5039                  pavam usthad school kandittillallo  Negative
2346   Oonth georg avanuvattanu avankurakkate pepatty...  Negative

[3824 rows x 2 columns]

In [57]:
import re
train_data['text'] = train_data['text'].apply(lambda x: x.lower())
train_data['target'] = train_data['target'].apply(lambda x: x.lower())
# removing special chars
train_data['text'] = train_data['text'].apply((lambda x: re.sub('[^a-zA-z0-9\s]','',x)))
# removing consecutive letters
train_data['text'] = train_data['text'].apply((lambda x: re.sub(r'(.)\1+', r'\1',x)))

train_data['target'] = train_data['target'].apply((lambda x: re.sub(r'\s+', '', x, flags=re.I)))

train_data.head()

text    target
438          natelulengile pothu samuhathil parayan patu   neutral
9389          vilainm vilainte monum orumich padkuayrikm   neutral
385        kerala politicsile shigandi enu vazhthapedate  negative
10218                           ne troln alne enke aryam   neutral
11091  likes um subscribers um kuravanelum viewers ne...  negative

In [58]:
val_data['text'] = val_data['text'].apply(lambda x: x.lower())
val_data['target'] = val_data['target'].apply(lambda x: x.lower())
# removing special chars
val_data['text'] = val_data['text'].apply((lambda x: re.sub('[^a-zA-z0-9\s]','',x)))
# removing consecutive letters
val_data['text'] = val_data['text'].apply((lambda x: re.sub(r'(.)\1+', r'\1',x)))

val_data['target'] = val_data['target'].apply((lambda x: re.sub(r'\s+', '', x, flags=re.I)))

val_data.tail()

text    target
10442  elavarum inghane fukruvine kutam parayale like...   neutral
14631                           eniku onu suport cheyamo   neutral
4897                                     muslim myranmar  negative
5039                      pavam usthad schol kanditilalo  negative
2346      onth georg avanuvatanu avankurakate pepatypole  negative

In [61]:
test_data['text'] = test_data['text'].apply(lambda x: x.lower())
test_data['target'] = test_data['target'].apply(lambda x: x.lower())
# removing special chars
test_data['text'] = test_data['text'].apply((lambda x: re.sub('[^a-zA-z0-9\s]','',x)))
# removing consecutive letters
test_data['text'] = test_data['text'].apply((lambda x: re.sub(r'(.)\1+', r'\1',x)))

test_data['target'] = test_data['target'].apply((lambda x: re.sub(r'\s+', '', x, flags=re.I)))

test_data.tail()

text    target
11284                               endh verupikalada  negative
11964  uyo ende mone kuduthal kuduthal pratheshikunu   positive
5390                                    abilash sanki   neutral
860                            ayala ara thuranu vita   neutral
15795                                          poliye  positive

In [62]:
val_data.target.unique()

array(['negative', 'neutral', 'positive'], dtype=object)

In [63]:
data = pd.concat([train_data, val_data], ignore_index=True)
data = pd.concat([data, test_data], ignore_index=True)
print(data)

                                                    text    target
0            natelulengile pothu samuhathil parayan patu   neutral
1             vilainm vilainte monum orumich padkuayrikm   neutral
2          kerala politicsile shigandi enu vazhthapedate  negative
3                               ne troln alne enke aryam   neutral
4      likes um subscribers um kuravanelum viewers ne...  negative
...                                                  ...       ...
19117                                  endh verupikalada  negative
19118     uyo ende mone kuduthal kuduthal pratheshikunu   positive
19119                                      abilash sanki   neutral
19120                             ayala ara thuranu vita   neutral
19121                                             poliye  positive

[19122 rows x 2 columns]


In [64]:
from keras.preprocessing.text import Tokenizer
#from keras.preprocessing.sequence import pad_sequences
from keras.utils.data_utils import pad_sequences

max_features = 1500
tokenizer = Tokenizer(num_words=max_features, split=' ')
tokenizer.fit_on_texts(data['text'].values)
X= tokenizer.texts_to_sequences(data['text'].values)
X = pad_sequences(X)
print(X[:2])
print(len(X))

[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0 1428   80  405]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0 1096]]
19122


In [65]:
Y = pd.get_dummies(data['target']).values
print(Y)
len(Y)

[[0 1 0]
 [0 1 0]
 [1 0 0]
 ...
 [0 1 0]
 [0 1 0]
 [0 0 1]]


19122

In [66]:
train = len(train_data)
val = len(val_data)

In [67]:
X_train = X[:train]
Y_train = Y[:train]

print(len(X_train))
print(len(Y_train))

X_val = X[train : (train+val)]
Y_val = Y[train : (train+val)]

print(len(X_val))
print(len(Y_val))

X_test = X[(train+val) : ]
Y_test = Y[(train+val) : ]

print(len(X_test))
print(len(Y_test))

11473
11473
3824
3824
3825
3825


In [68]:
from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Embedding, Bidirectional , Dropout , LSTM

In [71]:
model = Sequential()
model.add(Embedding(max_features, 256))
model.add(Bidirectional(LSTM(128)))
model.add(Dense(128))    #for LSTM 4
model.add(Dense(3,activation='softmax'))
model.compile(loss = 'categorical_crossentropy', optimizer='rmsprop',metrics = ['accuracy'])
print(model.summary())

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, None, 256)         384000    
                                                                 
 bidirectional_3 (Bidirectio  (None, 256)              394240    
 nal)                                                            
                                                                 
 dense_6 (Dense)             (None, 128)               32896     
                                                                 
 dense_7 (Dense)             (None, 3)                 387       
                                                                 
Total params: 811,523
Trainable params: 811,523
Non-trainable params: 0
_________________________________________________________________
None


In [80]:
model.fit(X_train, Y_train, epochs = 50, batch_size= 32 ,verbose = 1 , validation_data=(X_val,Y_val))

Epoch 1/50
359/359 [==============================] - 89s 248ms/step - loss: 0.2245 - accuracy: 0.9014 - val_loss: 1.6638 - val_accuracy: 0.6187
Epoch 2/50
359/359 [==============================] - 93s 260ms/step - loss: 0.2178 - accuracy: 0.9010 - val_loss: 1.6960 - val_accuracy: 0.6294
Epoch 3/50
359/359 [==============================] - 96s 269ms/step - loss: 0.2095 - accuracy: 0.9062 - val_loss: 1.6976 - val_accuracy: 0.6318
Epoch 4/50
359/359 [==============================] - 91s 253ms/step - loss: 0.2057 - accuracy: 0.9090 - val_loss: 1.7041 - val_accuracy: 0.6226
Epoch 5/50
359/359 [==============================] - 92s 257ms/step - loss: 0.2015 - accuracy: 0.9101 - val_loss: 1.7621 - val_accuracy: 0.6237
Epoch 6/50
359/359 [==============================] - 98s 274ms/step - loss: 0.1953 - accuracy: 0.9129 - val_loss: 1.8032 - val_accuracy: 0.6234
Epoch 7/50
359/359 [==============================] - 96s 267ms/step - loss: 0.1930 - accuracy: 0.9130 - val_loss: 1.7089 - val_ac

In [87]:
print(X_test)

[[   0    0    0 ...    0  477   62]
 [   0    0    0 ...    0  131  231]
 [   0    0    0 ...  129  908  231]
 ...
 [   0    0    0 ...    0    0 1136]
 [   0    0    0 ...    0    0  249]
 [   0    0    0 ...    0    0 1282]]


In [81]:
Y_pred = model.predict(X_test)

120/120 [==============================] - 8s 69ms/step


In [82]:
classes = ['negative','neutral','positive']

In [83]:
len(Y_pred)

3825

In [84]:
print(Y_pred)

[[3.9490857e-03 2.8145596e-04 9.9576950e-01]
 [9.9296314e-01 3.0321185e-04 6.7336638e-03]
 [9.9973512e-01 2.4535859e-04 1.9590025e-05]
 ...
 [7.4026403e-03 9.8509562e-01 7.5017093e-03]
 [3.8957417e-01 6.0691130e-01 3.5144966e-03]
 [6.6013658e-06 5.6339145e-06 9.9998772e-01]]


In [85]:
import numpy as np
pred_class = []
for item in Y_pred:
  index = np.argmax(item)
  pred_class.append(classes[index])
  #pred_class.append(index)

print(pred_class)

['positive', 'negative', 'negative', 'negative', 'positive', 'negative', 'positive', 'positive', 'positive', 'neutral', 'negative', 'neutral', 'positive', 'positive', 'neutral', 'positive', 'neutral', 'negative', 'negative', 'positive', 'negative', 'neutral', 'negative', 'neutral', 'neutral', 'negative', 'neutral', 'negative', 'positive', 'positive', 'positive', 'negative', 'positive', 'positive', 'neutral', 'negative', 'neutral', 'positive', 'positive', 'neutral', 'neutral', 'negative', 'neutral', 'negative', 'positive', 'negative', 'negative', 'negative', 'neutral', 'positive', 'positive', 'negative', 'neutral', 'positive', 'positive', 'negative', 'negative', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'positive', 'negative', 'negative', 'neutral', 'negative', 'positive', 'negative', 'negative', 'negative', 'negative', 'negative', 'positive', 'negative', 'negative', 'positive', 'positive', 'neutral', 'positive', 'neutral', 'neutral', 'neutral', 'positive',

In [86]:
print("\n Training Accuracy :" , model.evaluate(X_train, Y_train  , verbose = 2)[1] ,"\n")
print("\n Testing Accuracy :" , model.evaluate(X_test, Y_test , verbose = 2)[1] )

359/359 - 20s - loss: 0.1501 - accuracy: 0.9269 - 20s/epoch - 55ms/step

 Training Accuracy : 0.9268717765808105 

120/120 - 7s - loss: 1.7418 - accuracy: 0.6230 - 7s/epoch - 55ms/step

 Testing Accuracy : 0.6230065226554871


In [89]:
dx=["nannayittund","myru","kollam","iyalkk nanamille myran"]
df = pd.DataFrame(dx, columns=['text'])
print(df)

                     text
0            nannayittund
1                    myru
2                  kollam
3  iyalkk nanamille myran


In [90]:
from keras.preprocessing.text import Tokenizer
#from keras.preprocessing.sequence import pad_sequences
from keras.utils.data_utils import pad_sequences


max_features = 1500
tokenizer = Tokenizer(num_words=max_features, split=' ')
tokenizer.fit_on_texts(df['text'].values)
X1= tokenizer.texts_to_sequences(df['text'].values)
X1= pad_sequences(X1)
print(X1[:2])
print(len(X1))

[[0 0 1]
 [0 0 2]]
4


In [93]:
Y1=model.predict(X1)

1/1 [==============================] - 1s 862ms/step


In [94]:
import numpy as np
pred_class = []
for item in Y1:
  index = np.argmax(item)
  pred_class.append(classes[index])
  #pred_class.append(index)

print(pred_class)

['negative', 'negative', 'neutral', 'positive']


In [79]:
from sklearn.metrics import classification_report
print(classification_report(pred_class,test_data['target']))

              precision    recall  f1-score   support

    negative       0.67      0.60      0.63      1378
     neutral       0.53      0.54      0.53      1273
    positive       0.69      0.77      0.73      1174

    accuracy                           0.63      3825
   macro avg       0.63      0.63      0.63      3825
weighted avg       0.63      0.63      0.63      3825

